spring:
  application:
    name: product-sample-api-1

  datasource:
    url: jdbc:postgresql://localhost:5435/ecom_db
    username: postgres1
    password: postgres@istad

  jpa:
    hibernate:
      ddl-auto: update   # use update (not create-drop for now)
    show-sql: true
    properties:
      hibernate:
        format_sql: true

server:
  port: 8888